# Generated by Django 4.0.1 on 2022-01-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_name_school_school_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
